version: "3.8"

services:
  backend:
    depends_on:
      - db
      - prometheus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "2112:2112"
    env_file:
      - .env
    networks:
      - monitoring

  db:
    image: postgres:15
    container_name: messenger-api-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
